import { SectionFrame } from '@/components/layout/SectionFrame';
import { ScenarioCard } from '@/components/problem-explorer/ScenarioCard';
import { SystemModuleShell } from '@/components/problem-explorer/SystemModuleShell';
import { HudPanel } from '@/components/hud/HudPanel';
import { MicroLabel } from '@/components/hud/MicroLabel';
import { ConnectorLine } from '@/components/graphics/ConnectorLine';
import { scenarios, systemModules } from '@/data/foundation-fixtures';
import styles from './ProblemExplorerFoundation.module.scss';
export function ProblemExplorerFoundation(){return <SectionFrame id="change" number="02" eyebrow="ДИАГНОСТИКА ПРОЦЕССА" title="ЧТО МОЖНО ИЗМЕНИТЬ" className={styles.section}><div className={styles.grid}><div><p className={styles.intro}>Выберите задачу — система покажет, какие модули участвуют в её решении.</p><ul className={styles.scenarios}>{scenarios.map(([n,t,d],i)=><ScenarioCard key={n} number={n} title={t} description={d} selected={i===0}/>)}</ul></div><div className={styles.system}><MicroLabel priority={1}>STATIC FOUNDATION STATE</MicroLabel><div className={styles.modules}>{systemModules.map((label,i)=><SystemModuleShell key={label} label={label} active={[0,1,2,5].includes(i)}/>)}</div><div className={styles.cube} aria-label="Временный CubeCore shell"><span>BND</span><strong>ENGINE</strong><small>FIXTURE CORE</small></div><ConnectorLine className={styles.route1} active/><ConnectorLine className={styles.route2}/></div><HudPanel variant="architecture" className={styles.process}><MicroLabel priority={1}>ПРИМЕР СЦЕНАРИЯ</MicroLabel><h3>Автоматизация заявки</h3><ol>{['Форма / заявка','AI-анализ','База данных','Telegram','Результат'].map((item,i)=><li key={item}><span>{i+1}</span><strong>{item}</strong><small>{i===4?'Готовый результат или отчёт':'Статический этап процесса'}</small></li>)}</ol><p>Fixture показывает композицию и семантику. Resolver и смена сценариев появятся позже.</p></HudPanel></div></SectionFrame>}
