import { SectionFrame } from '@/components/layout/SectionFrame';
import { ProductDirectionCard } from '@/components/product-assembler/ProductDirectionCard';
import { OctagonalCore } from '@/components/product-assembler/OctagonalCore';
import { ConnectorLine } from '@/components/graphics/ConnectorLine';
import { HudPanel } from '@/components/hud/HudPanel';
import { MicroLabel } from '@/components/hud/MicroLabel';
import { productDirections, principles, workflowStages } from '@/data/foundation-fixtures';
import styles from './ProductAssemblerFoundation.module.scss';
export function ProductAssemblerFoundation(){return <SectionFrame id="products" number="03" eyebrow="ПРОДУКТОВАЯ АРХИТЕКТУРА" title="СОБИРАЕМ ПРОДУКТЫ ПОД КОНКРЕТНЫЕ ПРОЦЕССЫ" className={styles.section}><div className={styles.grid}><div className={styles.left}><p>Подбираем форму продукта и технологическую основу под рабочий процесс, а не наоборот.</p><div className={styles.metrics}><span>AI / WEB</span><span>TELEGRAM</span><span>API</span><span>CRM</span></div></div><div className={styles.assembly}><div className={styles.cards}>{productDirections.map(([t,d],i)=><ProductDirectionCard key={t} title={t} description={d} active={i===0}/>)}</div><OctagonalCore size={196} state="active" decorative={false}/><ConnectorLine className={styles.r1} active/><ConnectorLine className={styles.r2}/><ConnectorLine className={styles.r3}/><ConnectorLine className={styles.r4}/></div><div className={styles.right}><HudPanel className={styles.stack}><MicroLabel priority={1}>ПРЕДВАРИТЕЛЬНЫЙ СТЕК</MicroLabel><ul>{['TypeScript','React / Next.js','AI API','PostgreSQL','Docker','Nginx'].map(x=><li key={x}>{x}</li>)}</ul><small>Финальная архитектура уточняется после анализа процесса.</small></HudPanel><HudPanel className={styles.principles}><MicroLabel priority={1}>ПРИНЦИПЫ РАБОТЫ</MicroLabel><ul>{principles.map(x=><li key={x}><span>◇</span>{x}</li>)}</ul></HudPanel></div></div><div className={styles.workflow}><strong>КАК МЫ РАБОТАЕМ</strong>{workflowStages.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b>{i<workflowStages.length-1&&<i aria-hidden="true">→</i>}</div>)}</div></SectionFrame>}
