(() => {
  const root=document.documentElement,heroScroll=document.getElementById('heroScroll');
  const frames=[...document.querySelectorAll('[data-cube-state]')],stateLabel=document.getElementById('stateLabel'),titleLines=[...document.querySelectorAll('.title-line')],modules=[...document.querySelectorAll('[data-module]')],lines=[...document.querySelectorAll('[data-line]')],nodes=[...document.querySelectorAll('[data-node]')],taskItems=[...document.querySelectorAll('.task-list li')],flowSteps=document.getElementById('flowSteps'),flowDescription=document.getElementById('flowDescription');
  const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const stateNames=['01 / СОСТОЯНИЕ: СОБРАН','02 / СОСТОЯНИЕ: АКТИВИРОВАН','03 / СОСТОЯНИЕ: ЧАСТИЧНО РАСКРЫТ','04 / СОСТОЯНИЕ: SYSTEM MODE'];
  const flows={form:{steps:['Форма','AI-анализ','База','Telegram','Результат'],text:'Система принимает данные, анализирует их, сохраняет контекст и запускает следующий этап без ручной передачи между сервисами.'},telegram:{steps:['Mini App','Профиль','Оплата','Уведомление'],text:'Telegram становится полноценной точкой входа в продукт: от заявки до личного кабинета и повторного взаимодействия.'},web:{steps:['Интерфейс','API','Данные','AI-помощник'],text:'Веб-продукт соединяет интерфейс, бизнес-логику и данные в одну управляемую систему.'},api:{steps:['Сервис A','Webhook','Обработка','Сервис B'],text:'API-сценарий передаёт данные между сервисами, проверяет условия и фиксирует результат без ручного копирования.'},ai:{steps:['Контекст','Модель','Проверка','Действие'],text:'ИИ получает контекст процесса, формирует результат и передаёт его дальше только после заданных проверок.'},crm:{steps:['Карточка','Статус','История','Следующий шаг'],text:'Внутренняя система хранит рабочий контекст и помогает сотруднику быстро переходить к следующему действию.'}};
  let targetProgress=0,progress=0,targetX=0,targetY=0,pointerX=0,pointerY=0;
  const clamp=(v,a=0,b=1)=>Math.min(b,Math.max(a,v));
  const smoothstep=v=>{const t=clamp(v);return t*t*(3-2*t)};
  function updateScrollTarget(){const max=Math.max(1,heroScroll.offsetHeight-innerHeight);targetProgress=clamp(-heroScroll.getBoundingClientRect().top/max)}
  function weight(index,scaled){const distance=Math.abs(scaled-index);if(distance>=.86)return 0;return smoothstep((.86-distance)/.34)}
  function renderHero(){
    const scaled=progress*3;let best=0,bestIndex=0;
    frames.forEach((frame,index)=>{let w=weight(index,scaled);if(progress<.001&&index===0)w=1;if(progress>.999&&index===3)w=1;if(w>best){best=w;bestIndex=index}const depth=(index+1)*.28;frame.style.opacity=w.toFixed(4);frame.style.filter=`saturate(${1.02+progress*.08}) contrast(1.03) blur(${((1-w)*.65).toFixed(2)}px)`;frame.style.setProperty('--cube-x',`${pointerX*depth}px`);frame.style.setProperty('--cube-y',`${pointerY*depth*.8}px`);frame.style.setProperty('--cube-scale',`${1.01+progress*.018}`)});
    const system=smoothstep((progress-.72)/.16);root.style.setProperty('--progress',progress.toFixed(4));root.style.setProperty('--system',system.toFixed(4));root.style.setProperty('--px',(pointerX/10).toFixed(4));root.style.setProperty('--py',(pointerY/10).toFixed(4));stateLabel.textContent=stateNames[bestIndex];
    const titleExit=smoothstep((progress-.55)/.38);titleLines[0].style.transform=`translate3d(${-titleExit*34}px,${-titleExit*8}px,0)`;titleLines[1].style.transform=`translate3d(${titleExit*20}px,0,0)`;titleLines[2].style.transform=`translate3d(${-titleExit*38}px,${titleExit*10}px,0)`;titleLines.forEach(line=>line.style.opacity=String(1-titleExit*.28));
  }
  function setModule(name){modules.forEach(el=>el.classList.toggle('is-active',el.dataset.module===name));lines.forEach(el=>el.classList.toggle('is-active',el.dataset.line===name));nodes.forEach(el=>el.classList.toggle('is-active',el.dataset.node===name))}
  modules.forEach(module=>{const name=module.dataset.module;module.addEventListener('mouseenter',()=>setModule(name));module.addEventListener('focus',()=>setModule(name));module.addEventListener('mouseleave',()=>setModule(null));module.addEventListener('blur',()=>setModule(null));module.addEventListener('click',()=>{const target=document.querySelector(module.dataset.target)||document.querySelector('#projects');target.scrollIntoView({behavior:'smooth',block:'start'})})});
  function renderFlow(key){const item=flows[key]||flows.form;flowSteps.innerHTML=item.steps.map((step,i)=>`${i?'<i>→</i>':''}<span>${step}</span>`).join('');flowDescription.textContent=item.text}
  taskItems.forEach(item=>{const activate=()=>{taskItems.forEach(x=>x.classList.remove('is-active'));item.classList.add('is-active');renderFlow(item.dataset.flow)};item.addEventListener('mouseenter',activate);item.addEventListener('focus',activate);item.addEventListener('click',activate)});
  function tick(){progress+=(targetProgress-progress)*(reducedMotion?1:.075);pointerX+=(targetX-pointerX)*.055;pointerY+=(targetY-pointerY)*.055;renderHero();requestAnimationFrame(tick)}
  addEventListener('scroll',updateScrollTarget,{passive:true});addEventListener('resize',updateScrollTarget,{passive:true});addEventListener('pointermove',event=>{targetX=(event.clientX/innerWidth-.5)*10;targetY=(event.clientY/innerHeight-.5)*8},{passive:true});addEventListener('pointerleave',()=>{targetX=0;targetY=0;setModule(null)});if('scrollRestoration'in history)history.scrollRestoration='manual';scrollTo(0,0);renderFlow('form');updateScrollTarget();renderHero();tick();
})();
